### ISSUE TITLE
Tag migration guides with affected APIs

### ISSUE THREAD

**Issue by BD103** [bevyengine/bevy-website#1216]
## Problem

A common process after a new release is published is for library authors to go through the **entire** migration guide and manually update their code. This can take a large amount of time, especially if the majority of breaking changes do not affect the author. Release candidates attempt to alleviate some of the pressure by giving authors more time, but do not fix the underlying problem: **plugin authors should not have to read through migration guides that do not affect them.**

## Solution

In the future it would be amazing if an author could automatically check (and fix!) any breaking changes. While that may not be possible before 0.14, we can start along this path.

### `apis` field

I propose we add the `apis` field (please bikeshed this name! I don't really like it.) to [`_guides.toml`](https://github.com/bevyengine/bevy-website/blob/2b28aebe0b072d65c519def5e20152552f8b2abc/release-content/0.14/migration-guides/_guides.toml). It will be an array that specifies the absolute path of all changed APIs.

```toml
[[guides]]
title = "fix some typos"
url = "https://github.com/bevyengine/bevy/pull/12038"
areas = []
file_name = "12038_fix_some_typos.md"
# Renamed to Node2d::ContrastAdaptiveSharpening, fixing the typo.
apis = ["bevy::core_pipeline::core_2d::graph::Node2d::ConstrastAdaptiveSharpening"]

[[guides]]
title = "Update to fixedbitset 0.5"
url = "https://github.com/bevyengine/bevy/pull/12512"
areas = []
file_name = "12512_Update_to_fixedbitset_05.md"
# Access::grow was removed.
apis = ["bevy::ecs::query::Access::grow"]
```

For it to be added to the `apis` field it must:

1. Be an absolute path from the root `bevy` crate, as specific as possible.
    - If a trait method's function signature was changed, you would specify the path to the method, not the trait.
    - If an enum variant was removed, you would specify the path to that specific variant, not the enum.
    - If a public module was removed or renamed, you would specify the path to that module
2. Be the **old** path, not the new one.
    - The idea is that this field is used to search old code for items that need to be changed. There's no point mentioning the new API.
3. Use Rust's syntax for paths. ([Reference](https://doc.rust-lang.org/reference/paths.html))

### Reference and search bar

On the right side of the migration guide, there will be a "table of contents" of all changed APIs sorted in order of appearance. Clicking on a changed API, such as `bevy::ecs::query::Access::grow`, will jump you to you section discussing the changes.

Furthermore at the top of this table, there will be a search bar that you can enter in names for APIs and it will filter the results using `result.toLowerCase().includes(query.toLowerCase())`. For instance if `bevy::ecs::query::Access::grow` was removed, you could search `Access` and it would show up. You could also search `ECS::queRY`, but cannot search `ces` because it is not contained within the result.

(I chose `String.incudes` because it provides the best results for the least amount of effort. Matching exactly is not entirely useful, and fuzzing error-correcting search is too difficult. Also, `.toLowerCase()` is because `.includes()` is case-sensitive.)
