### ISSUE TITLE
Dynamic linking instructions broken for Windows

### ISSUE THREAD

**Issue by Alainx277** [bevyengine/bevy-website#131]
Following the setup guide for fast builds on windows leads to errors when using dynamic linking. There seem to be two issues, which both have the solution of turning off "share-generics" for windows builds  (bevyengine/bevy#1126, bevyengine/bevy#1110).

Maybe it would be good to offer a solution in the setup guide, or perhaps even temporarily turn off shared generics in the cargo config template.

**Comment by paul-hansen** [comment]
This should be working on Windows now afaik. I've been using it on Windows for awhile now.

The trick is that you _need_ these lines on Windows or it doesn't work:
```toml
# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
```

We should probably remove `Note that right now, this doesn't work on Windows` from the setup instructions from the book, and emphasize that the opt-level lines are needed for Windows.

See for more info see comments: https://github.com/bevyengine/bevy/issues/1110#issuecomment-1322645492 and https://github.com/bevyengine/bevy/issues/2921#issuecomment-1353395072
