### ISSUE TITLE
Write about how to reduce Wasm binary size

### ISSUE THREAD

**Issue by janhohenheim** [bevyengine/bevy-website#1537]
This would fit in with https://bevyengine.org/learn/quick-start/getting-started/setup/#compile-with-performance-optimizations

Something like @benfrankel's config:
```toml
# Optimize for size in wasm-release mode.
[profile.wasm-release]
inherits = "release"
opt-level = "z"
strip = "debuginfo"
```
which is then built by passing `--profile wasm-release` to `cargo-build`
