### ISSUE TITLE
LLD directly

### ISSUE THREAD

**Issue by axelkar** [bevyengine/bevy-website#1649]
Could LLD be used directly with the following? Why is clang required on Linux, but not Windows?
```toml
[target.x86_64-unknown-linux-gnu]
linker = "lld" # or ld.lld, not sure if just lld exists on all distros
```
