### ISSUE TITLE
Show example shader code in a separate code block

### ISSUE THREAD

**Issue by IceSentry** [bevyengine/bevy-website#456]
# Objective

The shader examples are missing the actual shader code which is a pretty important part of those examples. We should have a way to also copy the code from those files and show them in a code block below the current code block.

**Comment by BD103** [comment]
What if in the [example metadata](https://github.com/bevyengine/bevy/blob/e0778bf407631f9ae0f1e7326bb63e98d0e6fe87/Cargo.toml#L336-L340), you could specify a list of important related files that should also be shown on the website?

```toml
[package.metadata.example.shader_material]
name = "Shader Material"
# ...
related = ["assets/shaders/custom_material.wgsl"]
```
